import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'
import MediumCard from '../components/MediumCard'
import Faq from '../components/Faq.js'
import Footer from '../components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 className='text-2xl p-4 text-white font-serif text-center bg-neutral-600 '>ˇ_____©øffeetuu_____˘</h1>
        <Banner/>

        <main  className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section>
          <h2 className='text-3xl font-semibold '>
          Different Types of Coffee
          </h2>
          <div className='flex md:mt-16 space-x-3 overflow-scroll scrollbar-hide p-3'> 
            
            <MediumCard 
            
            />
        
          </div>

        </section>

        <section>
          <h2 className='text-4xl font-semibold py-8'>
           FAQ about Coffee
          </h2>
         <Faq/>
        </section>
    
        </main>
       
           <Footer/>
    </>
  )
}
